language: python
os:
  - linux
  - osx
  - windows
python:
  - "3.5"
  - "3.8"
  - "3.11"
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
install:
  - pip install -r requirements.txt
script: pytest
after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov
# Add emails to notify global users; otherwise, Travis CI sends emails to the committer and the commit authors
notifications: 
  email:
    recipients:
    - v37shah@uwaterloo.ca
    - d3diep@uwaterloo.ca
    on_success: always
    on_failure: always
# Slack notifications (if it is used in the future)
  # slack: 
   # on_success: always
   # on_failure: always   
