name: argos-translate-base-langs
base: core18
version: '1.0.0'
summary: Adds language support to argos-translate snap
description: |
  Supports translation between Arabic, Chinese, English, French, Russian, and Spanish
grade: stable
confinement: strict

parts:
  packages:
    source: packages
    plugin: dump
    organize:
      '*' : packages/

slots:
  argos-packages:
    interface: content
    content: argos-packages
    source:
      read:
        - $SNAP/packages 
