name: argos-translate
title: Argos Translate
base: core18 
version: '1.0.2' 
license: MIT
summary: Offline neural machine translation app
description: |
  [Docs](https://argos-translate.readthedocs.io) | [Website](https://www.argosopentech.com)

  Open-source offline neural machine translation app that allows installing packages to support new languages.
  
  Engilish↔French translation packaged with application with more translations available for download.
  
  Argos Translate supports installing model files which are a zip archive with an ".argosmodel" extension that contain an OpenNMT CTranslate model, a SentencePiece tokenization model, a Stanza tokenizer model for sentence boundary detection, and metadata about the model. Pretrained models can be downloaded [here](https://drive.google.com/drive/folders/11wxM3Ze7NCgOk_tdtRjwet10DmtvFu3i). To install a model click "Manage packages" from the toolbar in the GUI and select your model file. When running from a snap package models can be pre-packaged with the snap package or installed after installation to `$SNAP_USER_DATA`.
  
  Argos Translate also manages automatically pivoting through intermediate languages to translate between languages that don't have a direct translation between them installed. For example, if you have a es -> en and en -> fr translation installed you are able to translate from es -> fr as if you had that translation installed. This allows for translating between a wide variety of languages at the cost of some loss of translation quality.

icon: snap/gui/icon.png

grade: stable
confinement: strict

apps:
  argos-translate: 
    adapter: full
    command: desktop-launch $SNAP/bin/argos-translate
    environment:
      DISABLE_WAYLAND: 1
    plugs:
      - desktop
      - desktop-legacy
      - opengl
      - wayland
      - x11
       
# From snapcraft-desktop-helpers
# https://github.com/ubuntu/snapcraft-desktop-helpers
parts:
  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  argos-translate:
    after: [desktop-qt5]
    plugin: python
    python-version: python3
    source: .
    # Based on ericoporto/pyqthelloworld
    # https://github.com/ericoporto/pyqthelloworld
    build-packages:
      - python3
      - python3-pyqt5
      - execstack
    stage-packages:
      - python3
      - python3-pyqt5
      - libc-bin
      - locales

  model-files:
    source: packages
    plugin: dump
    organize:
      '*' : packages/

