on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  create-github-release:
    name: GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create Release
        run: gh release create ${{ github.ref }} --generate-notes
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
