on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  release:
    name: GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
	 repo_token: ${{ secrets.GITHUB_TOKEN }}
	 prerelease: false
      #- name: Create Release
      #  run: gh release create ${{ github.ref }} --generate-notes
      #  env:
      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
